# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: (PROD) GHD Management System Web App Firebase CI

on:
  push:
    branches: [ main ]
    paths:
      - Workspace/GHD_Management_System-Web_App-Client-Side/**
  pull_request:
    branches: [ main ]
    paths:
      - Workspace/GHD_Management_System-Web_App-Client-Side/**

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    defaults:
      run:
        working-directory: ./Workspace/GHD_Management_System-Web_App-Client-Side/ghd-management-system

    steps:
    - uses: actions/checkout@v2 # Checkout the repository
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g
    - name: npm install, build and test
      run: |
        npm install
        npm run build
    - name: Archive Build # Archiving the artifact to use in the next job (deploy)
      uses: actions/upload-artifact@v2
      with: 
        name: build
        path: ${{ github.workspace }}/Workspace/GHD_Management_System-Web_App-Client-Side/ghd-management-system/build
        
  deploy:
      name: Deploy
      needs: build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2 # Checkout the repository
        - name: Download Build # Extracting the build from the previous job
          uses: actions/download-artifact@v2
          with: 
            name: build
            path: ${{ github.workspace }}/Workspace/GHD_Management_System-Web_App-Client-Side/ghd-management-system/build
        - name: Deploy to Firebase
          uses: w9jds/firebase-action@master
          with:
            args: deploy --only hosting
          env:
            PROJECT_PATH: ./Workspace/GHD_Management_System-Web_App-Client-Side/ghd-management-system
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
            
