# GitHub Action Workflow - 
# Branch: MAIN
# Environment: PRODUCTION
# Web Application: GHD COVID19 Public Website Web App
# Purpose: Web app build check upon pull requests towards main branch

name: (PROD) GHD COVID19 Public Website Web App Build Check

# Action trigger configuration
on:
  pull_request:
    branches: [ main ]
    paths:
      - Workspace/GHD_Public_Website-Landing-Page-Client-Side/**

jobs:
  # Generate web app build source files
  build:

    # Operating system to run build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x] # Node.js version to run build
    
    # Default working sub directory to run build
    defaults:
      run:
        working-directory: ./Workspace/GHD_Public_Website-Landing-Page-Client-Side/ghd-public-website

    # Steps executed within the job
    steps:
    - uses: actions/checkout@v2 # Checkout the repository
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g
    - name: npm install, build and test
      run: |
        npm install
        npm run build

