# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: (QA) GHD Management System Web App Build Check

on:
  push:
    branches: [ develop ]
    paths:
      - Workspace/GHD_Management_System-Web_App-Client-Side/**

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    defaults:
      run:
        working-directory: ./Workspace/GHD_Management_System-Web_App-Client-Side/ghd-management-system

    steps:
    - uses: actions/checkout@v2 # Checkout the repository
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g
    - name: npm install, build and test
      run: |
        npm install
        npm run build
        
        
