# GitHub Action Workflow - 
# Branch: DEVELOP
# Environment: QA
# Web Application: GHD Management System Web App
# Purpose: Web app continuous integration / continuous deployment to firebase hosting using firebase CI

name: (QA) GHD Management System Web App Firebase CI

# Action trigger configuration
on:
  push:
    branches: [ develop ]
    paths:
      - Workspace/GHD_Management_System-Web_App-Client-Side/**

jobs:
  # Generate web app build source files
  build:

    # Operating system to run build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x] # Node.js version to run build

    # Default working sub directory to run build
    defaults:
      run:
        working-directory: ./Workspace/GHD_Management_System-Web_App-Client-Side/ghd-management-system

    # Steps executed within the job
    steps:
    - uses: actions/checkout@v2 # Checkout the repository
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g
    - name: npm install, build and test
      run: |
        npm install
        npm run build
    - name: Archive Build # Archiving the artifact to use in the next job (deploy)
      uses: actions/upload-artifact@v2
      with: 
        name: build
        path: ${{ github.workspace }}/Workspace/GHD_Management_System-Web_App-Client-Side/ghd-management-system/build
        
  # Deployment to firebase hosting
  deploy:
      name: Deploy
      needs: build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2 # Checkout the repository
        - name: Download Build # Downloading the build from the previous job
          uses: actions/download-artifact@v2
          with: 
            name: build
            path: ${{ github.workspace }}/Workspace/GHD_Management_System-Web_App-Client-Side/ghd-management-system/build
        - name: Deploy to Firebase
          uses: w9jds/firebase-action@master
          with:
            args: deploy --only hosting --project qa-ghd-management-system
          env:
            PROJECT_PATH: ./Workspace/GHD_Management_System-Web_App-Client-Side/ghd-management-system
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
            
