# GitHub Action Workflow - 
# Branch: DEVELOP
# Environment: QA
# Web Application: GHD Management System Web App
# Purpose: Web app build check upon pull requests towards develop branch

name: (QA) GHD Management System Web App Build Check

# Action trigger configuration
on:
  push:
    branches: [ develop ]
    paths:
      - Workspace/GHD_Management_System-Web_App-Client-Side/**

jobs:
  # Generate web app build source files
  build:

    # Operating system to run build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x] # Node.js version to run build

    # Default working sub directory to run build
    defaults:
      run:
        working-directory: ./Workspace/GHD_Management_System-Web_App-Client-Side/ghd-management-system

    # Steps executed within the job
    steps:
    - uses: actions/checkout@v2 # Checkout the repository
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g
    - name: npm install, build and test
      run: |
        npm install
        npm run build
        
      